### ISSUE TITLE
两个bug

### ISSUE THREAD

**Issue by pngfi** [Jay-Goo/RangeSeekBar#10]
1. 关于setvalue方法
 if (callback != null) {
            if (mSeekBarMode == 2) {
                callback.onRangeChanged(this, leftSB.currPercent, rightSB.currPercent, false);
            }else {
                callback.onRangeChanged(this, leftSB.currPercent, leftSB.currPercent, false);
            }
        }
我看其他时候传的都是实际值，这里怎么是百分比

2.BitmapFactory.decodeResource(getResources(), mThumbId)
这个方法只能解析原生的bitmap，不能解码自定义的Drawable，建议
getResources().getDrawable(mThumbResId)并将其转为bitmap
public static Bitmap drawableToBitmap (Drawable drawable) {
        Bitmap bitmap = null;

        if (drawable instanceof BitmapDrawable) {
            BitmapDrawable bitmapDrawable = (BitmapDrawable) drawable;
            if(bitmapDrawable.getBitmap() != null) {
                return bitmapDrawable.getBitmap();
            }
        }

        if(drawable.getIntrinsicWidth() <= 0 || drawable.getIntrinsicHeight() <= 0) {
            bitmap = Bitmap.createBitmap(1, 1, Bitmap.Config.ARGB_8888); // Single color bitmap will be created of 1x1 pixel
        } else {
            bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888);
        }

        Canvas canvas = new Canvas(bitmap);
        drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
        drawable.draw(canvas);
        return bitmap;
    }

**Comment by JinJieGu** [comment]
@pngfi 你提PR吧，我看下如果没问题，就合在一起了。
