### ISSUE TITLE
Disable tick mark

### ISSUE THREAD

**Issue by Etio39** [Jay-Goo/RangeSeekBar#100]
Hi Jay-Goo,

I'd like to know if there is a way to disable tick marks. I don't want to show them but the space is still there.

Here you can see the white space I don't want (the red line is where I want the layout to stop) :
![Capture d’écran 2019-06-04 à 17 08 29](https://user-images.githubusercontent.com/38917120/58890813-a8dcf400-86eb-11e9-802c-b327338cdf99.png)

Thanks in advance.

**Comment by JinJieGu** [comment]
that is not tick marks space, it's indicator's height. This design is to ensure that the progress is in the middle. I will consider how to optimize it better in the future versions.

**Comment by Etio39** [comment]
Ok thank you

**Comment by JinJieGu** [comment]
One temporary solution is to set a specific height, it will not double  indicator's height.
like this: `android:layout_width="100dp"`
