### ISSUE TITLE
How to make indicator text bold?

### ISSUE THREAD

**Issue by ghost** [Jay-Goo/RangeSeekBar#109]
Hello! 
Thanks for such a great library.

I am using version 3.0.0

I have a question about the text of the indicator. I looked for methods but found only these:

> rangeSeekBar.setIndicatorText();
> rangeSeekBar.setIndicatorTextDecimalFormat();
> rangeSeekBar.setIndicatorTextStringFormat();

**Comment by SayedElabady** [comment]
You can use `setTypeface`  

in the passed typeface you can change the style as you want for example 

`		rangeSeekBar.setTypeface(Typeface.create(Typeface.SANS_SERIF , Typeface.BOLD))
`
you change this bold to any style you want

**Comment by MarFry** [comment]
@devoma 
`rangeSeekBar?.rightSeekBar?.setTypeface(Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD))`
