### ISSUE TITLE
HI! I have some problem

### ISSUE THREAD

**Issue by ZenASI** [Jay-Goo/RangeSeekBar#111]
你好! 我在設置移動間距->rsb_tick_mark_number = 100，時無效果。請問是還要再JAVA內設置細節，才有效果嗎? 謝謝

`<com.jaygoo.widget.RangeSeekBar`
`android:layout_width="match_parent"`
`android:layout_height="wrap_content"`
`app:rsb_mode="range"`
`app:rsb_indicator_width="@dimen/dp40"`
`app:rsb_indicator_height="@dimen/dp40"`
`app:rsb_indicator_show_mode="alwaysShow"`
`app:rsb_tick_mark_mode="other"`
`app:rsb_tick_mark_number="100"` 
`app:rsb_min="0"`
`app:rsb_max="2000"/>`

**Comment by aicaprio** [comment]
同上，rsb_tick_mark_number这个属性在RangeSeekBar找不到。是替换成别的了？
