### ISSUE TITLE
Thumb not rounded

### ISSUE THREAD

**Issue by tantai24495** [Jay-Goo/RangeSeekBar#115]
- The thumb in your demo app, i saw it not really rounded, on top and bottom of the thumb it's not rounded. 
- You can run your demo app, go page 2 (Range), and zoom to check the thumb 
- Check my pic, thanks
![image](https://user-images.githubusercontent.com/40748200/65103053-30c6df80-d9f7-11e9-8ac6-7ac9f3243ef6.png)

**Comment by JinJieGu** [comment]
the picture is not round,not bug
