### ISSUE TITLE
Is it possible to implement an onStopTrackingTouch?

### ISSUE THREAD

**Issue by audibert** [Jay-Goo/RangeSeekBar#12]
Hi,

Is it possible to add support for the function onStopTrackingTouch present in the standard SeekBar ? (i.e. it is called when the user stops changing the progress of the bar). It really helps when we need to change an attribute only when the user sets the value "as final", without having to write to a complex object each time the range changes.

Thanks in advance!

**Comment by JinJieGu** [comment]
Of course, I will implement next version! Thank you for feedback!
