### ISSUE TITLE
如果我想要禁止拖动怎么处理

### ISSUE THREAD

**Issue by songjianzaina** [Jay-Goo/RangeSeekBar#128]
-  Make sure you compiled the latest version.(确保你编译了最新版本)
- Describe the scenarios or operates when crash happened as much as possible(pictures would be better).(尽可能详细的描述崩溃时的场景或操作，最好有截图)
- Tell me your device type and Android OS version is very helpful.(设备信息和系统版本也比较有用)
- Paste your xml or java code.(粘贴你的代码)
- Paste the crash log.(粘贴你的崩溃日志)
- Please be polite.(请保持礼貌)

**Comment by JinJieGu** [comment]
setEnabled，SeekBar怎么做的，这个还是怎么做
