### ISSUE TITLE
How to always enable the shape on the top of thumb ?

### ISSUE THREAD

**Issue by rajeshkumarkhadka** [Jay-Goo/RangeSeekBar#14]
Always show the shape on the top of the thumb drawable.

**Comment by JinJieGu** [comment]
you can use the  `progressHintMode="alwaysShow"` like  seekbar2 in [activity_main.xml](https://github.com/Jay-Goo/RangeSeekBar/blob/master/app/src/main/res/layout/activity_main.xml#L33:24)`

**Comment by rajeshkumarkhadka** [comment]
it only shows aftertouch on seek bar. I want to show before touching on seek bar.

**Comment by JinJieGu** [comment]
Not support, it will be supported in the next version!

**Comment by rajeshkumarkhadka** [comment]
Any tweak would be very helpful @JinJieGu.

**Comment by JinJieGu** [comment]
The new great version is coming soon in a week ! Please keep your attention ~
