### ISSUE TITLE
[question] how to programmatically change drawable of app:rsb_thumb_drawable

### ISSUE THREAD

**Issue by nashihu** [Jay-Goo/RangeSeekBar#160]
hello, thanks for the library,

i have a requirement from user about how do i make the `app:rsb_thumb_drawable` (or attached below in red circle) is changed when it's clicked by the user? i've tried but still no luck, thank you

<img width="300" alt="Screen Shot 2021-07-25 at 17 28 38" src="https://user-images.githubusercontent.com/35857544/126896065-da361cf3-e929-47be-890f-f6fd19c32734.png">

**Comment by kavitamp** [comment]
@nashihu Did you try `rangeSeekBar.leftSeekBar.setThumbDrawableId(R.drawable.your_drawable, seekbar.thumbWidth, seekbar.thumbHeight)`?

**Comment by nashihu** [comment]
didn't see that i should call `leftSeekBar` first. 

it works now, thanks @kavitamp
