### ISSUE TITLE
VerticalSeekbar

### ISSUE THREAD

**Issue by ljxzhuce123** [Jay-Goo/RangeSeekBar#19]
请问是否可以设置成垂直的？如果不行，请问有写过这样的吗？谢谢！

**Comment by JinJieGu** [comment]
可以尝试使用View自带旋转属性`android:rotation = "90"`

**Comment by ljxzhuce123** [comment]
您好，旋转过来却无法滑动，请问该怎么解决呢？谢谢！



在 2017-12-29 14:06:50，"谷进杰" <notifications@github.com> 写道：


可以尝试使用View自带旋转属性android:rotation = "90"

**Comment by JinJieGu** [comment]
需要对控件滑动做处理，暂时不支持，下个版本会考虑加入，请继续关注

**Comment by JinJieGu** [comment]
you can use the latest version, It can solve your need！
