### ISSUE TITLE
我设置hideProgressHint为true的时候，ProgressHint的高度仍然存在

### ISSUE THREAD

**Issue by careylee0127** [Jay-Goo/RangeSeekBar#2]
如题：代码中
 mHintBGHeight = mHintBGHeight == 0 ? (mCursorPaint.measureText("国") * 3) : mHintBGHeight;
设置ProgressHint高度少了hide的判断~ 目前我通过gradle集成的~ 设置app:hintBGHeight > 0 可以规避到这个问题

**Comment by JinJieGu** [comment]
已经修复了，谢谢，以后有问题你也可以通过给我提PR

**Comment by JinJieGu** [comment]
@careylee0127 已经修复了，谢谢，以后有问题你也可以通过给我提PR
