### ISSUE TITLE
如何把它进行竖着滑动

### ISSUE THREAD

**Issue by nanchen2251** [Jay-Goo/RangeSeekBar#21]

**Comment by JinJieGu** [comment]
暂时不支持，下个版本考虑加入

**Comment by nanchen2251** [comment]
这是一个相当不错的库，非常期待能尽快支持到垂直，另外除了支持滑动，如果还能支持像 SeekBar 那样直接点击出进度也不错！

**Comment by JinJieGu** [comment]
you can use the latest version, It can solve your need！
