### ISSUE TITLE
最低版本号16  是不是有点高啊

### ISSUE THREAD

**Issue by shenjiajun53** [Jay-Goo/RangeSeekBar#25]

**Comment by JinJieGu** [comment]
不高了吧，现在基本都是5.0以上的系统了，微信也不过支持到4.3，支持到4.1.3感觉应该够用了。当然如果你有低版本需求也可以告诉我。

**Comment by JinJieGu** [comment]
哈哈，早就是4.3了，不过这个控件往下兼容倒也没啥影响
