### ISSUE TITLE
Change hint background color

### ISSUE THREAD

**Issue by NikHec** [Jay-Goo/RangeSeekBar#27]
Is there a way to change hint background color?

**Comment by elriczhan** [comment]
Just create a  9-patch file and use that method 
public void setProgressHintBGId(int mProgressHintBGId)

**Comment by NikHec** [comment]
It doesn't work for me. It still shows the default green one.
Or if I try to change it in the xml file it crashes.

**Comment by JinJieGu** [comment]
you can use the latest version, It can solve your problem！
