### ISSUE TITLE
android 7.0以上系统，DEMO不显示

### ISSUE THREAD

**Issue by Christain** [Jay-Goo/RangeSeekBar#3]
android 7.0以上系统，DEMO中的第一个示例没有显示出来，onMeasure()方法是调用了的，高度值也是有的，麻烦解答一下

**Comment by JinJieGu** [comment]
@Christain 我看了一下，因为Android 7.0以后，优化了View的绘制，onMeasure和onSizeChanged调用顺序有所变化，导致最小高度heightNeeded没有正确的算出来。
Android7.0以下：onMeasure--->onSizeChanged--->onMeasure
Android7.0以上：onMeasure--->onSizeChanged
