### ISSUE TITLE
Change default min max value to time value

### ISSUE THREAD

**Issue by Updates3** [Jay-Goo/RangeSeekBar#30]
Hello Jay-Goo,

I'm using this library for time range bar, now we want to convert default value to time value,
like suppose i set max value 24 then your library return to me time value(ex., 23.50, 22.30,20.20 or 20.12 but not 23.90, 22.81, 23.92, 22.75,21. etc.,).

Thanks.

**Comment by JinJieGu** [comment]
You can use the `setIndicatorTextDecimalFormat`or`setIndicatorTextDecimalFormat` to convert your indicator value.

**Comment by Updates3** [comment]
Hello JinJieGu,
I'm using seekbar3.setIndicatorTextDecimalFormat("00.00"); but it not convert to time value,
still showing me value like 17.68 etc.
![screenshot_20180518-101718 1](https://user-images.githubusercontent.com/36408303/40226903-9df86556-5aaa-11e8-9168-6673ab0d1850.png)

**Comment by JinJieGu** [comment]
ok, you can format the value by yourself,  and then use `setIndicatorText` to change the value in onRangeChanged.

```
 seekbar4.setOnRangeChangedListener(new OnRangeChangedListener() {
            @Override
            public void onRangeChanged(RangeSeekBar view, float min, float max, boolean isFromUser) {
                float timeValue = (int)min + (min - (int)min) * 0.6f;
                DecimalFormat df = new DecimalFormat("0.00");
                view.setIndicatorText(df.format(timeValue));
            }
         ...
        });
```

**Comment by JinJieGu** [comment]
use the SeekBar's setIndicator can solve your problem.
example：
`view.getLeftSeekBar().setIndicatorText()`

**Comment by Updates3** [comment]
Hello **JinJieGu**,
Thanks for your back to back reply,
Now it's working fine as i want, so **THANKS A LOT**,
Suggestion:=> please add time range fields in doc(as i did) so user can know in this library also working for TIME RANGE BAR.

Thanks **JinJieGu**.

**Comment by Updates3** [comment]
Hello JinJieGu,
above your suggestion view.getLeftSeekBar().setIndicatorText() is working fine for left seekbar, and i did same in right seek bar like view.getRightSeekBar().setIndicatorText(), but now when i just touch at left seekbar then change right seekbar value 23.59 to 23.35,

My code is:=>

public void onRangeChanged(RangeSeekBar view, float min, float max, boolean isFromUser) {
float timeValue = (int) min + (min - (int) min) * 0.6f;
        float timeValueMax = (int) max + (max - (int) max) * 0.6f;
        DecimalFormat df = new DecimalFormat("0.00");
        view.getLeftSeekBar().setIndicatorText(df.format(timeValue));
        view.getRightSeekBar().setIndicatorText(df.format(timeValueMax));
},

after touch at left seek bar right seekbar value change 23.59 to 23.35, and i drag to left and right then right seekbar value stop at 23.59 not 23.35.

Please help.

Thanks.
![screenshot_20180621-160054](https://user-images.githubusercontent.com/36408303/41714856-476705a0-756f-11e8-8878-9b7f1e1c28c9.png)
![screenshot_20180621-160101](https://user-images.githubuser
![screenshot_20180621-162311](https://user-images.githubusercontent.com/36408303/41714915-793632ea-756f-11e8-955e-035b29ef79a3.png)
content.com/36408303/41714859-4793d846-756f-11e8-93e6-66b265471c6e.png)
![screenshot_20180621-160106](https://user-images.githubusercontent.com/36408303/41714860-47c310ca-756f-11e8-8476-e9371cf06109.png)

**Comment by sampie926** [comment]
Any solution?

**Comment by sampie926** [comment]
I set app:rsb_max="23.984" because the seekbar is still works with normal float.
