### ISSUE TITLE
How Set costume font(Typeface) in  Left & Right Seek Bar?

### ISSUE THREAD

**Issue by Updates3** [Jay-Goo/RangeSeekBar#31]
**Hello JinJieGu,**

I want to set font(Typeface) in min & max text,
how can i do it?

**Thanks.**

**Comment by JinJieGu** [comment]
not support now, I will add it in next version

**Comment by JinJieGu** [comment]
Support now ! Please use the release version .you can get usage in [FAQ](https://github.com/Jay-Goo/RangeSeekBar/wiki/FAQ)
