### ISSUE TITLE
提交几处 bug

### ISSUE THREAD

**Issue by merhong2012** [Jay-Goo/RangeSeekBar#32]
@JinJieGu 
你好，我发现几个BUG：

1. 除setValue外的其他 set 方法需要调用setRangeRules，否则不会生效。

2. rsb_mode为range时，`tickMarkNumberonRangeChanged`回调的 max值永为最大值，原因是`getRangeSeekBarState()`方法中`rightSeekBarState.value = range`的问题。改为`rightSeekBarState.value = -offsetValue + minPositiveValue + range * rightSB.currPercent;`则解决问题

3. `getRangeSeekBarState() `方法中为rightSeekBarState赋值错误，`leftSeekBarState.indicatorText = tickMarkTextArray[index].toString();`应改为  `rightSeekBarState.indicatorText = tickMarkTextArray[index].toString();`

**Comment by JinJieGu** [comment]
@merhong2012 Thank you very much ! I will fix it in the  next version!

**Comment by JinJieGu** [comment]
The set methods does not take effect immediately，you should call `rangeSeekBar.invalidate()` to make it work.
