### ISSUE TITLE
Padding to the thumb indicator

### ISSUE THREAD

**Issue by ritesh94** [Jay-Goo/RangeSeekBar#33]
@JinJieGu  How do I add **padding** to thumb indicator?

Suppose I have a RangeBar from `0 to 200000`. the thumb indicator area becomes too small to slide through the range.!!

If there is no way to set padding for a thumb indicator, can you suggest some workaround to get going?

**Comment by JinJieGu** [comment]
Off course you can!
Please use these attributes to set the thumb indicator's  padding.
```
        app:rsb_indicator_padding_left="10dp"
        app:rsb_indicator_padding_right="10dp"
        app:rsb_indicator_padding_top="0dp"
        app:rsb_indicator_padding_bottom="0dp"
```
You can know more infomation about the attributes'  usage in the [wiki](https://github.com/Jay-Goo/RangeSeekBar/wiki/Attribute-methods)

Hope can help you~

**Comment by ritesh94** [comment]
@JinJieGu 
I tried it setting the below attributes  via XML and also programatically through java code. 
I am afraid its not working.

 ```
        app:rsb_indicator_padding_left="10dp"
        app:rsb_indicator_padding_right="10dp"
        app:rsb_indicator_padding_top="0dp"
        app:rsb_indicator_padding_bottom="0dp"
```

**Comment by Updates3** [comment]
also not working left and right seekbar padding & margin for me
