### ISSUE TITLE
Can not add library via gradle

### ISSUE THREAD

**Issue by ekizy** [Jay-Goo/RangeSeekBar#34]
Can not add library to the gradle when i paste below command in dependencies. Is there a problem with library ?

    implementation 'com.github.Jay-Goo:RangeSeekBar:v2.0.1'

**Comment by ritesh94** [comment]
@ekizy What is the error you are getting ?
Have you tried the adding repositories block ?

 allprojects {
		repositories {
			**maven { url 'https://jitpack.io' }**
		}
	}

	dependencies {
	        implementation 'com.github.Jay-Goo:RangeSeekBar:v2.0.1'
	}

**Comment by ekizy** [comment]
Thanks for the help. Now i would be able to use it. Can i ask another question? How can we grow the size of thumb when it is pressed or moved. In this library thumb's size is always same

**Comment by JinJieGu** [comment]
Sorry ,not support now, I will add the option in the future.

**Comment by ekizy** [comment]
Thanks again for the answer and also as a final question. Can we only show integer values in seekbar ? In the indicator text it shows float values.

**Comment by JinJieGu** [comment]
you can use the ` rangeSeekBar.setIndicatorTextStringFormat()`and `rangeSeekBar.setIndicatorTextDecimalFormat()` to format the text, you can get more useage in the [wiki](https://github.com/Jay-Goo/RangeSeekBar/wiki) and demo.

**Comment by JinJieGu** [comment]
You can use the `setOnRangeChangedListener` to get current progress from seekbar.
```
 rangeSeekBar.setOnRangeChangedListener(new OnRangeChangedListener() {
            @Override
            public void onRangeChanged(RangeSeekBar view, float min, float max, boolean isFromUser) {
           //min is left seekbar value, max is right seekbar value
            }

            @Override
            public void onStartTrackingTouch(RangeSeekBar view,  boolean isLeft) {
                //start tracking touch
            }

            @Override
            public void onStopTrackingTouch(RangeSeekBar view,  boolean isLeft) {
                //stop tracking touch
            }
        });
```

**Comment by JinJieGu** [comment]
This variable name is not very good, I'll optimize it in the next version.
