### ISSUE TITLE
初始显示值

### ISSUE THREAD

**Issue by chenkexu** [Jay-Goo/RangeSeekBar#36]
如何设置双向滑块 初始的位置？？？如何获得滑块滑动之后的刻度值？？

**Comment by JinJieGu** [comment]
Please see the wiki [FAQ](https://github.com/Jay-Goo/RangeSeekBar/wiki/FAQ) to get the useage

**Comment by chenkexu** [comment]
设置初始值只能设置float吗？  我的刻度如果有中文呢？

**Comment by JinJieGu** [comment]
It supports your need，please see the demo.

Please confirm you have read the wiki and demo before you question
