### ISSUE TITLE
Can u increase hit area of thumb ?

### ISSUE THREAD

**Issue by hscoraline** [Jay-Goo/RangeSeekBar#37]
First sorry for my english, i used your library for my project, i really like it, but one small thing, it's too difficult for hit the thumb, my thumb size is 12dp.

**Comment by JinJieGu** [comment]
I'm sorry to tell you not to support it for this version. It will be improved in the  next version. You can pay attention to the [ToDoList](https://github.com/Jay-Goo/RangeSeekBar/projects/1) to get the latest progress!

**Comment by hscoraline** [comment]
thanks, now i'm waiting for the next version :laughing:  your library very helpful :+1:  1 :star:

**Comment by JinJieGu** [comment]
Thank you for waiting，it support now, you can see the [Guide](https://github.com/Jay-Goo/RangeSeekBar/wiki/FAQ)
