### ISSUE TITLE
Is there a way to divide this seekbar into checkpoints?

### ISSUE THREAD

**Issue by karanthakakr04** [Jay-Goo/RangeSeekBar#4]
i'm developing an app which display food item prices in android seek-bar..food items has 3 main prices(small, regular and large). I wanted the seek bar to move only to 0th(small price), 100th(large price) and middle(regular price) positions only, and display the price of regular if seek-bar is in middle position, etc...
How can I achieve this using this repo?
Any help would be appreciated.

**Comment by JinJieGu** [comment]
@karanthakakr04 you can try to use the cellMode like this:
 
<com.jaygoo.widget.RangeSeekBar
        android:id="@+id/seekbar4"
        android:layout_width="match_parent"
        android:layout_height="80dp"
        app:markTextArray="@array/wordsArray"
        app:lineColorSelected="@color/colorPrimary"
        app:lineColorEdge="@color/colorSeekBarDefault"
        app:textPadding="17dp"
        app:cells="4"
        app:hideProgressHint="true"
        app:textSize="12sp"
        app:hintBGHeight="28dp"
        app:seekBarHeight="8dp"
        app:thumbSize="26dp"
        app:cellMode="other"
        app:seekBarMode="single"
        />

it will divide the seekbar

**Comment by karanthakakr04** [comment]
Alrighty! Thank you so much. This works well.
