### ISSUE TITLE
如何动态设置步长呢？

### ISSUE THREAD

**Issue by ttttupup** [Jay-Goo/RangeSeekBar#40]
想动态设置步长，也就是递增滑动，刚开始增速慢，后面增速变快，大概看了下setCellsCount，但是不生效。谢谢

**Comment by YinHAHA** [comment]
请问步长的问题你设置上了吗？

**Comment by ttttupup** [comment]
没有设置步长，把显示数据改一下也可以。

**Comment by YinHAHA** [comment]
如果我想设置一个textview显示选择的区间，怎么弄？

![b258de51-a75b-45e2-aaae-3e416121a02b](https://user-images.githubusercontent.com/21334507/41648696-35987764-74ac-11e8-9149-68f4e05a574e.png)

**Comment by ttttupup** [comment]
这个是刻度的吗？刻度的这个库支持的。 mSeekBar.setRightProgressDescription("不限"); mSeekBar.setValue(0f, 50f);

**Comment by ttttupup** [comment]
支持。他有个自带的，你也可以自己在上面加一个 
app:rsb_progressHintResId="@drawable/air"
app:rsb_progressHintMode="alwaysShow"   这2个就是那个提示

**Comment by YinHAHA** [comment]
用下面属性这个，如果我是双向的Seekbar就会显示两个提示值，我想显示一个，并且在选择区间中间显示一个。。。。
![image](https://user-images.githubusercontent.com/21334507/41650315-4ef369ae-74b0-11e8-9dd8-f9665de809a3.png)

**Comment by ttttupup** [comment]
你在这个布局上面加个textview放中间，app:rsb_progressHintMode="alwaysShow" 这个改成总是隐藏，然后 mSeekBar.setOnRangeChangedListener(new RangeSeekBar.OnRangeChangedListener() {
            @Override
            public void onRangeChanged(RangeSeekBar view, float min, float max, boolean isFromUser) {}}监听里更改textview的值就可以了

**Comment by YinHAHA** [comment]
不是在整个布局的最中间，是在选择区间的中间，这个显示值的View是根据选择区间位置变化而变化的

**Comment by ttttupup** [comment]
一样的，你用个布局包一下，textview 在RangeSeekBar 上面中间就可以了。这个RangeSeekBar能嵌套在很多布局中的

**Comment by YinHAHA** [comment]
那怎么确保这个TextView显示在所选布局的中间呢？

**Comment by ttttupup** [comment]
<TextView
            android:id="@+id/tv_price_range"
            android:layout_width="match_parent"
            android:layout_height="40dp"
            android:gravity="center" />  好多种方法啊

**Comment by JinJieGu** [comment]
@YinHAHA 暂时不支持这样显示布局，ttttupup的这个方案不可行哦，以后可以考虑把这个功能加进来
