### ISSUE TITLE
Is there no getValue? (also: numbers after decimal point AND indicator corner radius)

### ISSUE THREAD

**Issue by sicksugar** [Jay-Goo/RangeSeekBar#41]
I only found setValue but no getValue.
There's getMinProgress and getMaxProgress, but in a slider of 0-10 they will only return 0 and 10.
The most basic functionality of a slider is to be able to give me the value the user chose.
What am i missing?

I had to set a listener and take the **min** value from it, and put it into a variable.
But this means that this variable changes all the time when the user slides the slider.
I just want to take the final/current value and use it for something.

Two other smaller issues:
1) I can set the seekbar to display a specific number format (for example 0.1 instead of 0.12345), but the actual value remains 0.12345 when i try to use the seekbar value elsewhere. is there a way to control the output or the intervals?
2) I see on the first demo gif, the 3rd indicator has a corner radius, but i could not find a way to set this in the XML or in the JAVA. Is there a way?

**Comment by hamzaahmedkhan** [comment]
You should add getValue(), its really necessary. Like I want to calculate BMI on a Button action and wants to getValue from seekbar.

**Comment by Elank0521** [comment]
I think should add "getMinValue()" and "getMaxValue()", I want to use them, but they don't exist. Thanks.

**Comment by bahmandamia6982** [comment]
Thanks for great library:
but I really need `getMinValue()` and `getMaxValue()` !

**Comment by sonshark** [comment]
rangeSeekBar.setValue(0, 3000000);
        rangeSeekBar.setIndicatorTextDecimalFormat("0");
        rangeSeekBar.setOnRangeChangedListener(new OnRangeChangedListener() {
            @Override
            public void onRangeChanged(RangeSeekBar view, float leftValue, float rightValue, boolean isFromUser) {

          
                    minPrice = leftValue ;
                    maxPrice = rightValue ;
        

            }

            @Override
            public void onStartTrackingTouch(RangeSeekBar view, boolean isLeft) {
                //do what you want!!
            }

            @Override
            public void onStopTrackingTouch(RangeSeekBar view, boolean isLeft) {
                //do what you want!!
            }
        });
