### ISSUE TITLE
我想用View显示我选择的区间

### ISSUE THREAD

**Issue by YinHAHA** [Jay-Goo/RangeSeekBar#45]
![image](https://user-images.githubusercontent.com/21334507/41648751-628a37d0-74ac-11e8-85ed-378d74e5c3c4.png)

**Attention**
>You can know almost all useage and questions in the [WIKI](https://github.com/Jay-Goo/RangeSeekBar/wiki), please confirm you have read them before you question!

**Environment**
 - Device: [Google Pixel2]
 - OS: [6.0.1]
 - Library Version: [2.0.2]

**Description**
What's wrong with you ?

**Screenshots**

**注意**
>你几乎可以从 [WIKI](https://github.com/Jay-Goo/RangeSeekBar/wiki)获取几乎所有的用法和常见问题, 在你提问之前请确认你已经看过以上内容!

**环境**
 - 设备: [Google Pixel2]
 - 系统: [6.0.1]
 - 库版本: [2.0.2]

**描述**

**截图**

**Comment by JinJieGu** [comment]
暂时不支持这样的显示，请持续关注此库未来的更新

**Comment by JinJieGu** [comment]
v3.0.0 已支持通过自定义指示器满足你的需求
