### ISSUE TITLE
set margin or padding between left and right seek bar(overriding left & right seekbar).

### ISSUE THREAD

**Issue by Updates3** [Jay-Goo/RangeSeekBar#46]
Hello jay-goo,
I'm using this library, it's working fine, but overriding text left & right range seek bar,
i set  app:rsb_indicator_padding_bottom="0dp"
                        app:rsb_indicator_padding_left="20dp"
                        app:rsb_indicator_padding_right="20dp"
                        app:rsb_indicator_padding_top="0dp"
                        app:rsb_indicator_margin="8dp"
in xml file & also set in java file:=>
        binding.amftMonRangeBar.getLeftSeekBar().setIndicatorPaddingLeft(20);
        binding.amftMonRangeBar.getLeftSeekBar().setIndicatorPaddingRight(20);
        binding.amftMonRangeBar.getRightSeekBar().setIndicatorPaddingLeft(20);
        binding.amftMonRangeBar.getRightSeekBar().setIndicatorPaddingRight(20);
        binding.amftMonRangeBar.getLeftSeekBar().setIndicatorMargin(8);
        binding.amftMonRangeBar.getRightSeekBar().setIndicatorMargin(8);

but both left & right indicator text overriding.

How can i keep space between left & right seekbar.
see below attachment.

Thanks.
![screenshot_20180622-115629 1](https://user-images.githubusercontent.com/36408303/41761020-72d3de9e-7613-11e8-9d2a-523f45bff49c.png)
![screenshot_20180622-115619 1](https://user-images.githubusercontent.com/36408303/41761037-814226de-7613-11e8-8fff-18760de100ed.png)
![screenshot_20180622-115609 1](https://user-images.githubusercontent.com/36408303/41761045-88c662c6-7613-11e8-928f-90c0f5f1cd0d.png)

**Comment by JinJieGu** [comment]
Ok,guys,The `rsb_indicator_padding` is  padding of the text in indicator,not for the two thumbs's margin.
u can set the `rsb_range_interval`to set the thumbs's minimum interval
