### ISSUE TITLE
Min Progress & Max Progress not getting correctly set.

### ISSUE THREAD

**Issue by harshadbagul** [Jay-Goo/RangeSeekBar#48]
**Attention**
>Min Progress & Max Progress not getting correctly set.

**Environment**
 - Device: [Red MI Note 4]
 - OS: [6.0.1]
 - Library Version: [2.0.2]

**Description**
I want to set minProgress & maxProgress values problematically , i don't want to set them through xml.
As i am using the methods as follows,
  seekbar_search_euronorm.minProgress = 1f
  seekbar_search_euronorm.maxProgress = 10f

It sets the min,max but **as soon as i change range of seek bar it shows me value from 1-100 within** seekbar , but given limit for min = 1 & max = 10 which i previously set by methods.
 
**Screenshots**
No screenshots

**Comment by JinJieGu** [comment]
please use `setRange(min, max)` to limit

**Comment by harshadbagul** [comment]
@JinJieGu  there is no such method like setRange(min, max).

I found setRangeRules( min, max, reserve, tickMarkNumber)  this method on range seek bar object.
