### ISSUE TITLE
Progress radius doesn't work!

### ISSUE THREAD

**Issue by AhmedMouradDev** [Jay-Goo/RangeSeekBar#50]
**Environment**
 - Device: Huawei Y7 Prime
 - OS: [8.0.0]
 - Library Version: [2.0.2]

**Description**

Can't manage to add progress radius, i tries these approaches:

```
<com.jaygoo.widget.RangeSeekBar
                android:id="@+id/add_found_age_seek_bar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:rsb_max="30"
                app:rsb_min="0"
                app:rsb_mode="range"
                app:rsb_indicator_show_mode="alwaysShow"
                app:rsb_indicator_height="32dp"
                app:rsb_range_interval="1"
                app:rsb_indicator_padding_left="8dp"
                app:rsb_indicator_padding_right="8dp"
                app:rsb_progress_color="@color/colorAccent"
                app:rsb_tick_mark_mode="number"
                app:rsb_tick_mark_number="1"
                app:rsb_progress_radius="0.8dp"  // or 50dp
                app:rsb_tick_mark_text_array="@array/age_marks"/>
```
or this:
```
seekBar.setProgressRadius(0.8f);
seekBar.invalidate();
```

Neither of them seem to make the slightest difference...

Shouldn't the purple square have a radius now?

**Screenshots**
![image](https://user-images.githubusercontent.com/29189251/42719394-176696ec-8715-11e8-8a80-d743812030aa.png)

**Comment by JinJieGu** [comment]
I tested it works well,maybe your progress height is too small, the radius is not so obvious

**Comment by JinJieGu** [comment]
try to set  `rsb_progress_height` to make it obvious

**Comment by AhmedMouradDev** [comment]
@JinJieGu That worked! but how do i control the indicator corner radius?

**Comment by JinJieGu** [comment]
not support now, I will add it in next version

**Comment by AhmedMouradDev** [comment]
Great, Thanks!

**Comment by JinJieGu** [comment]
support now !
