### ISSUE TITLE
Mark Text goes off the widget

### ISSUE THREAD

**Issue by donpaul120** [Jay-Goo/RangeSeekBar#53]
**Attention**
>You can know almost all useage and questions in the [WIKI](https://github.com/Jay-Goo/RangeSeekBar/wiki), please confirm you have read them before you question!

**Environment**
 - Device: [Google Pixel2]
 - OS: [6.0.1]
 - Library Version: [2.0.2]

**Description**
rsb_tick_mark_text_margin doesn't work as intended. goes way above the widget and gone.

```
 <com.jaygoo.widget.RangeSeekBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="4dp"
        android:layout_marginStart="4dp"
        android:layout_marginTop="4dp"
        app:fontFamily="@font/mrworking_font"
        app:layout_constraintLeft_toLeftOf="@id/fault_create_priority_lbl"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/fault_create_priority_lbl"
        app:rsb_mode="single"
        app:rsb_tick_mark_gravity="center"
        app:rsb_tick_mark_mode="other"
        app:rsb_tick_mark_number="3"
        app:rsb_tick_mark_text_array="@array/priority"
        app:rsb_tick_mark_text_margin="16dp"
        app:rsb_tick_mark_text_size="14sp" />
```

**Screenshots**
![screenshot_1532395268](https://user-images.githubusercontent.com/6430195/43111305-79d74936-8ee8-11e8-8a71-c65c1d52a84d.png)

**Comment by JinJieGu** [comment]
please use the release version
