### ISSUE TITLE
How to draw nine-patch indicator as PopupWindow?

### ISSUE THREAD

**Issue by AlexEvtushik** [Jay-Goo/RangeSeekBar#56]
Hey @JinJieGu, firstly thanks a lot for your lib, but I have a small trouble with an indicator.

View of RangeSeekBar with nine-patch indicator takes a lot of space, do you have ability to show indicators as PopupWindow like on screenshot below:

![untitled](https://user-images.githubusercontent.com/10709817/43777173-b21da330-9a5a-11e8-92bb-5b810b18507e.png)

Or maybe you know how to do it ?

**Comment by JinJieGu** [comment]
This requirement is somewhat complicated.I‘m sorry not support it for the time being.

**Comment by JinJieGu** [comment]
V3.0.0 already supports meeting your needs through custom indicators,you can try it
