### ISSUE TITLE
Keep Showing values of badges 

### ISSUE THREAD

**Issue by myJarvis** [Jay-Goo/RangeSeekBar#6]
Hi  i am using rangeseekbar , and keep want to show the values on top of the badges , currently value only comes when i scroll , how i can the selected current value all the times on top of badges.

**Comment by JinJieGu** [comment]
@myJarvis Do you want to show the thumb all the time?

**Comment by myJarvis** [comment]
Yes exactly I want to show thumb all the times with selected values
respective way.

**Comment by JinJieGu** [comment]
OK,I get. I will add the function in a week,If you are in a hurry to use it,you can fork my project and add it firstly.

**Comment by myJarvis** [comment]
Sure , will do it once I get few moments , running short with respect to
time in current project.

**Comment by JinJieGu** [comment]
@myJarvis if u can add the function ,welcome to push PR to me

**Comment by myJarvis** [comment]
Okay will do once get time will update you

**Comment by myJarvis** [comment]
if using two thumbs in a seekbar (in range case ) , uses thum always show property , so it shows same value for both thumbs , you need to check first the type of range bar  , then , if its range type you need to set the respective value as hint of thumbs .
