### ISSUE TITLE
Setting Integer Intervals

### ISSUE THREAD

**Issue by ensarbaylar** [Jay-Goo/RangeSeekBar#60]
**Environment**
 - Device: [Google Pixel2]
 - OS: [x]
 - Library Version: [2.0.4]

**Description**
I am having difficulties with setting integer intervals. I want users to select a distance with 50km intervals. But it acts different then I expected

**Screenshots**
`mDistanceRangeSeekBar = (RangeSeekBar) v.findViewById(R.id.options_fragment_distance_range_bar);
        mDistanceRangeSeekBar.setIndicatorTextDecimalFormat("0");
        mDistanceRangeSeekBar.setRange(50,500);
mDistanceRangeSeekBar.setRangeInterval(50);`

**Comment by JinJieGu** [comment]
if you want to set the step ,you can use the `rsb_tick_mark_number` ，the Interval just for the minimum distance
