### ISSUE TITLE
请问可以设置步长吗？

### ISSUE THREAD

**Issue by YangMian** [Jay-Goo/RangeSeekBar#62]
你好，这个裤子写得很好，但是我找不到可以设置步长的方法， 您能提供一下吗

我的RangeSeekBar 区间范围是0 - 10000， 需要每次滑动的最小单位是50 ， 不是现在默认的1

**Comment by JinJieGu** [comment]
支持的，你可以使用`rsb_tick_mark_number`设置等分的份数
