### ISSUE TITLE
Ticks on the rangebar

### ISSUE THREAD

**Issue by chakradhar451** [Jay-Goo/RangeSeekBar#63]
Hi, 
I loved this RangeSeekBar. But can I have points or tick marks on the range bar just like in the attached screenshot? 
![seekbar](https://user-images.githubusercontent.com/23308910/45015018-0c8f9f00-b03e-11e8-8d2c-9639a06b56fb.png)

**Comment by JinJieGu** [comment]
not support change the marks position
