### ISSUE TITLE
I need set secondary seekbar. how to implement?

### ISSUE THREAD

**Issue by farzadnone** [Jay-Goo/RangeSeekBar#7]
hi, thank you for useful **RangeSeekBar** library. can you add secondary bar on this RangeSeekBar? i need to it. thanks

sb bg      ------------------------------
sb rang   -------|----------|------------
sb sec     -------|~~~~~~|------------

**Comment by JinJieGu** [comment]
sorry,I can't understandthe diffrence of "rang"and "sec"? Can you describe it more clearly?
