### ISSUE TITLE
不支持RTL

### ISSUE THREAD

**Issue by excitedhaha** [Jay-Goo/RangeSeekBar#78]
如题，在阿语环境下，控件需要RTL显示

**Comment by JinJieGu** [comment]
暂不提供支持，

**Comment by AlaaZarifa** [comment]
I found a way to acheive RTL support 
Just set the `scaleX` to `-1` when it's an RTL state and that's it.

**code snippet**

```
if (getAppLang().equalsIgnoreCase("ar")) {
    priceRangeSeekbar.setScaleX(-1);
 }
```
