### ISSUE TITLE
Data binding?

### ISSUE THREAD

**Issue by atasoglou** [Jay-Goo/RangeSeekBar#85]
How does data-binding work?

**Comment by prabhusns33** [comment]
// Binding Utils class

    @BindingAdapter("rangeBarListeners")
    public static void setRangeBarFormatListener(RangeSeekBar rsb, RangeBarRangeChange listener) {
        if (rsb == null) return;
        rsb.setTypeface(Typeface.DEFAULT_BOLD);
        rsb.getLeftSeekBar().setTypeface(Typeface.DEFAULT_BOLD);
        rsb.setIndicatorTextDecimalFormat("0");
        rsb.setIndicatorTextStringFormat("%s°C");
        rsb.setOnRangeChangedListener(new OnRangeChangedListener() {
            @Override
            public void onRangeChanged(RangeSeekBar view, float leftValue, float rightValue, boolean isFromUser) {
                listener.onRangeChangedListener(view, leftValue, rightValue, isFromUser);
            }

            @Override
            public void onStartTrackingTouch(RangeSeekBar view, boolean isLeft) {
            }

            @Override
            public void onStopTrackingTouch(RangeSeekBar view, boolean isLeft) {
            }
        });





// interface 
public interface RangeBarRangeChange {
    public void onRangeChangedListener(RangeSeekBar view, float leftValue, float rightValue, boolean isFromUser);
}


//XML
            rangeBarListeners="@{customDialogVM::rangeListener}"
