### ISSUE TITLE
How to display only decimal values in indicator?

### ISSUE THREAD

**Issue by Rajesh-solulab** [Jay-Goo/RangeSeekBar#94]
I did check all attrs and found there is no way to display only integer value in indicator, please help to get it done

**Comment by chenineazeddine** [comment]
Hi! 
from your host activity or fragment get a reference to the seeker view then set the indicator text decimal format using this method:
` seek_bar.setIndicatorTextDecimalFormat("0")`

**Comment by chenineazeddine** [comment]
> I did check all attrs and found there is no way to display only integer value in indicator, please help to get it done
Hi!
from your host activity or fragment get a reference to the seeker view then set the indicator text decimal format using this method:
`seek_bar.setIndicatorTextDecimalFormat("0")`
