### ISSUE TITLE
目前Thumb 默认都必须是正方形icon,有时候设计稿是矩形的。

### ISSUE THREAD

**Issue by Raynor999** [Jay-Goo/RangeSeekBar#98]
**Description**
见Title, 目前绘制Progress,设置Thumb 都是SquareIcon, 不支持非正方形。
eg:        

![image_2019-05-23_17-40-40](https://user-images.githubusercontent.com/12731440/58242729-ea7fad80-7d81-11e9-9d70-2f2229f623fc.png)

**Comment by JinJieGu** [comment]
矩形也可以用正方形切啊，有什么使用的问题吗

**Comment by Raynor999** [comment]
> 矩形也可以用正方形切啊，有什么使用的问题吗

切正方 width多余部分用 透明像素？如果高比宽大很多，    backgroundLineRect  计算progress 矩形绘制区是 - width/2 ，拖动到最右边或最左边，就会看起来，progress 少了一部分。

**Comment by Raynor999** [comment]
已经Fork修复了这个问题， 不过项目都是Kotlin 项目，copy java代码不好看，最好是作者能修复这个问题。
